_dashboard:
    resource: "@WedBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:     /

_calendar:
    resource: "@WedBundle/Controller/CalendarController.php"
    type:     annotation
    prefix:   /calendar

_billing:
    resource: "@WedBundle/Controller/BillingController.php"
    type:     annotation
    prefix:  /billing

_shoots:
    resource: "@WedBundle/Controller/ShootsController.php"
    type:     annotation
    prefix:  /shoots

clients:
    resource: "@WedBundle/Controller/ClientController.php"
    type:     annotation
    prefix:  /clients

bookings:
    resource: "@WedBundle/Controller/BookingController.php"
    type:     annotation
    prefix:  /bookings

types:
    resource: "@WedBundle/Controller/TypeController.php"
    type:     annotation
    prefix:  /types

packages:
    resource: "@WedBundle/Controller/PackageController.php"
    type:     annotation
    prefix:  /packages

mailbox:
    resource: "@WedBundle/Controller/MailboxController.php"
    type:     annotation
    prefix:  /mailbox